FROM node:20-slim

WORKDIR /app

RUN npm install -g pnpm

COPY pnpm-workspace.yaml ./
COPY pnpm-lock.yaml ./
COPY package.json ./
COPY packages/ ./packages/
COPY apps/web/ ./apps/web/

ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL

RUN pnpm install --no-frozen-lockfile
RUN pnpm --filter web build

WORKDIR /app/apps/web

EXPOSE 3000

CMD ["node_modules/.bin/next", "start"]