FROM node:20-slim

# cache bust
RUN echo "bust-1"


WORKDIR /app

RUN npm install -g pnpm

COPY pnpm-workspace.yaml ./
COPY pnpm-lock.yaml ./
COPY package.json ./
COPY packages/ ./packages/
COPY apps/web/ ./apps/web/

ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL

RUN pnpm install --no-frozen-lockfile
RUN pnpm --filter web build

RUN cp -r /app/apps/web/.next/static /app/apps/web/.next/standalone/.next/static
RUN cp -r /app/apps/web/public /app/apps/web/.next/standalone/public 2>/dev/null || true

EXPOSE 3000

ENV PORT=3000
ENV HOSTNAME=0.0.0.0

CMD ["node", "/app/apps/web/.next/standalone/server.js"]